name: ahn-tree
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - gdal
  - geopandas
  - ipympl
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - scikit-image
  - scipy
  - shapely
  - tqdm
  - contextily
  - matplotlib
  - pyshp
  - pip:
    - open3d
    - laspy[lazrs]
    - https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/releases/download/v0.1/upcp-0.1-py3-none-any.whl
