name: hgb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - geopandas
  - ipympl
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - scikit-image
  - shapely
  - tqdm
  - pip:
    - open3d
    - laspy[lazrs]
    - https://github.com/Amsterdam-AI-Team/Urban_PointCloud_Processing/releases/download/v0.1/upcp-0.1-py3-none-any.whl
